name: Run

env:
  TZ: Asia/Shanghai
  
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '55 00,15 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
