name: Run

env:
  TZ: Asia/Shanghai
  
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '00 01,15 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
      with:
          timezoneLinux: "Asia/Shanghai"
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
